version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9  # Changed from nodejs to python 3.9
    commands:
      - pip install aws-sam-cli  # Changed from npm install to pip install
  build:
    commands:
      - sam build --template sam-pipeline-demo/template.yml
      - sam package --s3-bucket sam-pipleline-skillu-demo --output-template-file packaged.yaml --template-file sam-pipeline-demo/template.yml
artifacts:
  files:
    - packaged.yaml
